//AddWatchWindowVars Build 1
expRemoveAll()
//Variables
expAdd ("TTPLPFC_lab.enum_lab",getNatural())
expAdd ("TTPLPFC_rlyConnect",getNatural())
expAdd ("TTPLPFC_vBus_sensed_Volts",getNatural())
expAdd ("TTPLPFC_ac_vol_sensed_Volts",getNatural())
expAdd ("TTPLPFC_iL1_sensed_Amps",getNatural())
expAdd ("TTPLPFC_iL2_sensed_Amps",getNatural())
expAdd ("TTPLPFC_vBus_sensed_pu",getNatural())
expAdd ("TTPLPFC_ac_vol_sensed_pu",getNatural())
expAdd ("TTPLPFC_iL1_sensed_pu",getNatural())
expAdd ("TTPLPFC_iL2_sensed_pu",getNatural())
expAdd ("TTPLPFC_ac_vol_senseOffset_pu",getNatural())
expAdd ("TTPLPFC_clearTrip", getNatural())
expAdd ("EPwm5Regs.TZFLG",getNatural())
expAdd ("EPwm6Regs.TZFLG",getNatural())
expAdd ("EPwm7Regs.TZFLG",getNatural())
expAdd ("TTPLPFC_duty1_DC_ref_pu",getNatural())
expAdd ("TTPLPFC_duty2_DC_ref_pu",getNatural())
expAdd ("TTPLPFC_duty_ref_pu",getNatural())
expAdd ("TTPLPFC_system_temp_pu",getNatural())
expAdd ("TTPLPFC_system_vref_165_pu",getNatural())
expAdd ("TTPLPFC_vbus2_pu",getNatural())
expAdd ("TTPLPFC_autoStartSlew",getNatural())
expAdd ("TTPLPFC_rlyConnect",getNatural())
expAdd ("TTPLPFC_ISR1_LoadingMax",getNatural())
expAdd ("TTPLPFC_ISR2_LoadingAvg_accountingForNesting",getNatural())
//variables for debugging startup
expAdd ("TTPLPFC_manualStop",getNatural())
expAdd ("TTPLPFC_timedRun_flag",getNatural())
expAdd ("TTPLPFC_timedRun_ms",getNatural())
expAdd ("TTPLPFC_timedRunCounter_ms",getNatural())
expAdd ("TTPLPFC_dutySlew_pu",getNatural())
