//AddWatchWindowVars Build 2
expRemoveAll()
//Variables
expAdd ("TTPLPFC_lab.enum_lab",getNatural())
expAdd ("TTPLPFC_board_Status.enum_boardStatus",getNatural())
expAdd ("TTPLPFC_rlyConnect",getNatural())
expAdd ("TTPLPFC_clearTrip", getNatural())
expAdd ("TTPLPFC_closeGiLoop", getNatural())
expAdd ("TTPLPFC_ac_cur_ref_pu",getNatural())
expAdd ("TTPLPFC_iL1_sensed_pu",getNatural())
expAdd ("TTPLPFC_iL2_sensed_pu",getNatural())
expAdd ("TTPLPFC_iL1_sensed_Amps",getNatural())
expAdd ("TTPLPFC_iL2_sensed_Amps",getNatural())
expAdd ("TTPLPFC_vBus_sensed_Volts",getNatural())
expAdd ("TTPLPFC_ac_vol_sensed_Volts",getNatural())
expAdd ("TTPLPFC_ac_volRms_sensed_Volts",getNatural())
expAdd ("TTPLPFC_ac_curRms_sensed_Amps",getNatural())
expAdd ("EPwm1Regs.TZFLG",getNatural())
expAdd ("EPwm2Regs.TZFLG",getNatural())
expAdd ("TTPLPFC_duty1_pu",getNatural())
expAdd ("TTPLPFC_duty2_pu",getNatural())
expAdd ("TTPLPFC_iL1_sensed_pu",getNatural())
expAdd ("TTPLPFC_iL2_sensed_pu",getNatural())
expAdd ("TTPLPFC_iL2_sensed_pu",getNatural())
expAdd ("TTPLPFC_autoStartSlew",getNatural())
expAdd ("TTPLPFC_updateCoefficientsCommand", getNatural())
expAdd ("TTPLPFC_gi_Kp_Ref", getNatural())
expAdd ("TTPLPFC_gi_Ki_Ref", getNatural())